### ISSUE TITLE
Is it possible to predict the interaction with true protein stucture

### ISSUE THREAD

**Issue by MinjieHu** [patrickbryant1/SpeedPPI#12]
Dear developer,

Thanks for this great tool!

Although Alphafold did a great job of predicting protein structure, sometimes the predicted structure could be different from the true structure. Considering a scenario,  I got a protein structure from wet-lab experiment and I want to predict the potential interaction proteins. Is it possible to modify some parts of this pipeline so that it can handle such tasks?

Thanks in advance for any help!

Minjie

**Comment by patrickbryant1** [comment]
Hi,

You request to bias the predictions according to some constraints. This is nothing that we provide, but you can have a look here: https://github.com/JeffSHF/ColabDock

Hope this helps!
