### ISSUE TITLE
Production speed and parallelizing

### ISSUE THREAD

**Issue by mcatto** [patrickbryant1/SpeedPPI#14]
Hi,

I am running a fasta of 6 proteins against a fasta with 22737 proteins, using create_ppi_some_vs_some.sh (times 3 as there are 3 fastas of 6 proteins each). At the current pace (~8 min per protein pair), it will be done in ~775 days for just one pairing of fastas. I am working on trying to run the prediction jobs in parallel, but am limited to only 18 jobs using the current partition. doing so can bring me to ~130 days. Please let me know if you have any suggestions to increase the prediction rate or is this expected? I am running this on a slurm cluster with parameters as follows.
#SBATCH --partition=gpu_p
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --gres=gpu:A100:1
#SBATCH --mem=100gb
#SBATCH --time=7-00:00:00

Thanks,
Michael

**Comment by patrickbryant1** [comment]
This is expected, I don't think you need 100 gb per run though since your GPU likely doesn't have this.

**Comment by mcatto** [comment]
Thank you! That makes sense. I will lower the memory request.
