### ISSUE TITLE
":" multimers

### ISSUE THREAD

**Issue by ghost** [patrickbryant1/SpeedPPI#15]
I apologize if I missed this in your paper or in the README, but are multimers allowed in anyway? I've tried using ":" in SequenceA:SequenceB. I see that ":" is treated as an invalid character. 

Just wanted to check if there's any other way before falling back to the slower AlphaFold.

**Comment by patrickbryant1** [comment]
This is only for multimers. You provide the sequences in individual fasta files. Perhaps it helps to go through the test case?
