### ISSUE TITLE
Does the used version of AF provide .sc files

### ISSUE THREAD

**Issue by KoussaiB** [patrickbryant1/SpeedPPI#17]
Hello, 

Thanks for this great tool!

I have question regarding the output,

I was wondering if we can edit the used alphafold model in this tool to also generate an .sc file in order to be able to filter with pae_interaction <10 as in https://github.com/nrbennet/dl_binder_design 

The thing is, I am running this tool as a part of an in-silico binder design pipeline and wanted to check if I can integrate this scoring function as apart of the output.

Best and thank you in advance!

**Comment by patrickbryant1** [comment]
Hi,

There is no PAE in this version of AF (this is the original). 

If you want to design binders, see : https://github.com/patrickbryant1/EvoBind

Hope this helps!

Patrick

**Comment by KoussaiB** [comment]
will try that, thank you for your help!
