### ISSUE TITLE
Versioning 

### ISSUE THREAD

**Issue by jowodo** [patrickbryant1/SpeedPPI#18]
Hi, 

I am a sysadmin on a HPC. When installing software we always install a specific version. This is not possible for SpeedPPI. 
It is rather simple to tag versions: 
```
git clone https://github.com/patrickbryant1/SpeedPPI
cd SpeedPPi
git log --graph --oneline # choose commit to tag
git checkout 37d0a03 # 37d0a03 is the chosen commit 
git tag v0.1.0
git push origin --tags
```
It would be greatly appreciated if you could tag previous versions and/or the latest version. See [this stackoverflow answer](https://stackoverflow.com/questions/18216991/create-a-tag-in-a-github-repository/18223354#18223354) for more info.

Thanks

**Comment by patrickbryant1** [comment]
Hi,

I tagged the latest commit as you suggested. Hope this makes things easier for you - you could also use the commit id as a version?

Best,

Patrick

**Comment by jowodo** [comment]
Thanks for the quick reply and the quick fix! 
Yes, I used the commit id, but it is not sortable.
