### ISSUE TITLE
SpeedPPI some_vs_some test failure

### ISSUE THREAD

**Issue by lucajovine** [patrickbryant1/SpeedPPI#2]
Hi @patrickbryant1 , I finally got round to installing SpeedPPI, but when I run the test I get the following:

[speedppi_test.log](https://github.com/patrickbryant1/SpeedPPI/files/11375443/speedppi_test.log)

**Comment by patrickbryant1** [comment]
Hi, in the log it says that the error is related to the installation of the packages somehow:
AttributeError: module 'collections' has no attribute 'Iterable'
How did you install your environment? Are you sure you have the right python version. A quick search shows that this may be related to python 3.10.

**Comment by lucajovine** [comment]
I just did "conda env create -f speed_ppi.yml", as by the instructions...

**Comment by patrickbryant1** [comment]
Yes, this should have been specified. I changed the yml to have python 3.9. I think whatever you have is used as default. Can you please try it again?

**Comment by lucajovine** [comment]
Hi again, the test is now producing prediction files, so using python 3.9 instead of 3.10 indeed seems to have fixed the issue. Thanks!!

**Comment by lucajovine** [comment]
One minor thing re: the described installation procedure, for the test to run I had to also do:
```
mv data/uniclust30/uniclust30_2018_08/* data/uniclust30/
rmdir data/uniclust30/uniclust30_2018_08
```
because the files are expected to be in data/uniclust30/

**Comment by patrickbryant1** [comment]
Great to hear! Thanks for the tip, updated this to simply be in "/data/uniclust30_2018_08"

**Comment by patrickbryant1** [comment]
I think this must be related to what you have installed locally since jax 0.4 is not supported here and not installed in the conda env. Make sure that your conda uses the packages installed in the SpeedPPI env.

**Comment by lucajovine** [comment]
Yes, I think it inherited it from my conda base... seems to be running again now, will confirm when it's done.

**Comment by lucajovine** [comment]
```
AttributeError: module 'numpy' has no attribute 'int'.
```

Do I also need a specific version of numpy? I have 1.23.5... which should be fine for numpy>=1.19.5

**Comment by patrickbryant1** [comment]
I have not seen this before, but it may be that numpy changed something in v.1.20 like it says. Could you try with 1.19.5?

**Comment by patrickbryant1** [comment]
Try with numpy<=1.23.2. This is the version I have. Otherwise I recommend installing the python pip env. There, all versions should work. The issues with incompatible versions arise with dependencies in the conda builds.
