### ISSUE TITLE
running time for test 

### ISSUE THREAD

**Issue by theammn** [patrickbryant1/SpeedPPI#24]
Hi, I want to use this pipeline for analysis PPI and to see how it works I installed it and made the test (some_vs_some) run, but it is running for more than 1day now, is it normal ? what is the expected running time ? 

thank you for your help, 

best, 
Thea

**Comment by patrickbryant1** [comment]
Hi,
No, probably you are not using GPU?

Best,

Patrick

**Comment by molecules** [comment]
@theammn As mentioned in the README, you can test if it's configured to use the GPU thus (assuming you're using `conda` and the environment is called `speed_ppi`):

```
conda activate speed_ppi
python3 ./src/test_gpu_avail.py
```
