### ISSUE TITLE
environment conflicts

### ISSUE THREAD

**Issue by theammn** [patrickbryant1/SpeedPPI#27]
Hi, 
I delete the environment in order to recreate it from scratch because something wasn't working when I ran the algorithm.
Now, when I want to reinstall by first git clone and install the yml file from the environment, it's not working and saying : 

Channels:
- conda-forge
- defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed
Channels:
- conda-forge
- defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed
 
LibMambaUnsatisfiableError: Encountered problems while solving:
  - package openmmforcefields-0.11.2-pyhd8ed1ab_1 requires ambertools >=20.0,<23, but none of the providers can be installed
 
Could not solve for environment specs
The following packages are incompatible
├─ ambertools ==23.3 py312h1577c9a_6 is requested and can be installed;
└─ openmmforcefields ==0.11.2 pyhd8ed1ab_1 is not installable because it requires
   └─ ambertools >=20.0,<23 , which conflicts with any installable versions previously reported.

**Comment by luxiangze** [comment]
Hello, how did you resolve this environment conflicts? I encountered the same problem as you.
