### ISSUE TITLE
uniclus30 (2018) vs uniref30 (2023)

### ISSUE THREAD

**Issue by rubenalv** [patrickbryant1/SpeedPPI#28]
Hello, I noted that the last update of uniclus30 is 2018, and on the download server https://uniclust.mmseqs.com/ they only provide the uniref30 clusters thereafter.
I would think that a more updated database would be preferable to a smaller but less updated one, with the compromise of losing some search speed. On your paper you mention that the reason for the uniclus30 choice is that AF uses three databases including uniref90, so I'd suppose that using the one with lower similarity threshold would still be an improvement. What's your advice?

**Comment by Rohit-Satyam** [comment]
They provide Uniref30 in the latest release: https://wwwuser.gwdguser.de/~compbiol/uniclust/2023_02/

**Comment by patrickbryant1** [comment]
Yes, you can change this if you like.
