### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by wosmanitx** [patrickbryant1/SpeedPPI#8]
Hello,
Does a docker image exist of this application?

**Comment by patrickbryant1** [comment]
Hi,
You can build the one from AF if you like:
Here is the Dockerfile: https://github.com/deepmind/alphafold/tree/main/docker
then do:
docker build -f docker/Dockerfile -t alphafold .

(See point 5 here: https://github.com/deepmind/alphafold/tree/main)

Hope this helps!
