### ISSUE TITLE
Macbook M2

### ISSUE THREAD

**Issue by apinedalucena** [patrickbryant1/SpeedPPI#9]
Is it possible to run speedppi in a macbook m2? As far as I know it is not possible to install CUDA drivers in these computers. Woul appreciate very much your feedback!

**Comment by patrickbryant1** [comment]
Hi, 
This is not possible unless you somehow build the drivers to work with your GPU, but I am not sure if this can be done. I recommend not getting a Mac for GPU tasks. SpeedPPI will still run without GPU, but it will be very slow (perhaps 100-1000x slower).
